insert into autor values (1, 'Belchior');
insert into autor values (2, 'Roberto Carlos');
insert into autor values (3, 'Tiririca');
insert into autor values (4, 'Tom Jobim');
insert into autor values (5, 'Caetano Veloso');
insert into autor values (6, 'Gilberto Gil');
insert into autor values (7, 'Zé Ramalho');
insert into autor values (8, 'Elba Ramalho');
insert into autor values (9, 'Marilia Mendonça');
insert into autor values (10, 'Jota e Jotinha');
insert into autor values (11, 'Ana Maria');
insert into autor values (12, 'O Rappa');
insert into autor values (13, 'Djavan');
insert into autor values (14, 'Seu Jorge');
insert into autor values (15, 'Ana Carolina');
insert into autor values (16, 'Maria Gadu');
insert into autor values (17, 'Tierry');
insert into autor values (18, 'Pablo do Arrocha');
insert into autor values (19, 'Asas Livres');
insert into autor values (20, 'Trio Xote Novo');
