DELETE FROM CD_CATEGORIA;
DELETE FROM MUSICA_AUTOR;

-- INSERT NA TABELA CATEGORIAS
INSERT INTO CD_CATEGORIA VALUES(1, 10.00, 14.99);
INSERT INTO CD_CATEGORIA VALUES(2, 15.00, 19.99);
INSERT INTO CD_CATEGORIA VALUES(3, 20.00, 29.99);
INSERT INTO CD_CATEGORIA VALUES(4, 30.00, 50);

-- INSERT NA TABELA MUSICA_AUTOR

INSERT INTO MUSICA_AUTOR VALUES (2, 1);
INSERT INTO MUSICA_AUTOR VALUES (3, 1);
INSERT INTO MUSICA_AUTOR VALUES (4, 1);
INSERT INTO MUSICA_AUTOR VALUES (5, 2);
INSERT INTO MUSICA_AUTOR VALUES (6, 3);
INSERT INTO MUSICA_AUTOR VALUES (7, 13);
INSERT INTO MUSICA_AUTOR VALUES (8, 13);
INSERT INTO MUSICA_AUTOR VALUES (9, 13);
INSERT INTO MUSICA_AUTOR VALUES (10, 14);
INSERT INTO MUSICA_AUTOR VALUES (11, 14);
INSERT INTO MUSICA_AUTOR VALUES (12, 11);
INSERT INTO MUSICA_AUTOR VALUES (13, 11);
INSERT INTO MUSICA_AUTOR VALUES (14, 11);
INSERT INTO MUSICA_AUTOR VALUES (15, 7);
INSERT INTO MUSICA_AUTOR VALUES (16, 7);
INSERT INTO MUSICA_AUTOR VALUES (17, 20);



