SELECT *FROM AUTOR
1INSERT INTO MUSICA_AUTOR VALUES (2, 1);
INSERT INTO MUSICA_AUTOR VALUES (3, 1);
INSERT INTO MUSICA_AUTOR VALUES (4, 1);
INSERT INTO MUSICA_AUTOR VALUES (5, 2);
INSERT INTO MUSICA_AUTOR VALUES (6, 3);
INSERT INTO MUSICA_AUTOR VALUES (7, 13);
INSERT INTO MUSICA_AUTOR VALUES (8, 13);
INSERT INTO MUSICA_AUTOR VALUES (9, 13);
INSERT INTO MUSICA_AUTOR VALUES (10, 14);
INSERT INTO MUSICA_AUTOR VALUES (11, 14);
INSERT INTO MUSICA_AUTOR VALUES (12, 11);
INSERT INTO MUSICA_AUTOR VALUES (13, 11);
INSERT INTO MUSICA_AUTOR VALUES (14, 11);
INSERT INTO MUSICA_AUTOR VALUES (15, 7);
INSERT INTO MUSICA_AUTOR VALUES (16, 7);
INSERT INTO MUSICA_AUTOR VALUES (17, 20);




1
1
1
1
1
1
1
1
1